vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix: /uploads/product_images
            upload_destination: '%kernel.project_dir%/public/uploads/product_images'
            directory_namer:
                service: App\Service\ProductImageDirectoryNamer
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
